databases:
  - name: decidedb
    plan: free
    databaseName: decidedb
    user: decide

services:
  - type: web
    plan: free
    name: decide
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn decide.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: decidedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
