databases:
  - name: decidedb
    plan: free
    region: frankfurt
    databaseName: decidedb
    user: decide

services:
  - type: web
    plan: free
    name: decide
    runtime: python
    region: frankfurt
    branch: main
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn decide.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: POETRY_VERSION
        value: 1.8.2
      - key: DATABASE_URL
        fromDatabase:
          name: decidedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
