# Generated by Django 5.0.3 on 2024-04-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='properties',
            field=models.JSONField(default=dict),
        ),
    ]
