# Generated by Django 5.0.3 on 2024-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='formula',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='idea',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idea',
            name='votes_count',
            field=models.IntegerField(default=0),
        ),
    ]
