# Generated by Django 5.0.3 on 2024-04-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_formula_idea_priority_idea_votes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='formula',
            field=models.TextField(blank=True, default=''),
        ),
    ]
