# Generated by Django 5.0.3 on 2024-04-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_alter_idea_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='properties',
        ),
    ]
