# Generated by Django 5.0.3 on 2024-04-08 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_remove_idea_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ideas.idea')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('idea', 'key')},
            },
        ),
    ]
