# Generated by Django 5.0.3 on 2024-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_ideaproperty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ideaproperty',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='idea',
            name='properties',
            field=models.ManyToManyField(related_name='ideas', to='ideas.ideaproperty'),
        ),
        migrations.RemoveField(
            model_name='ideaproperty',
            name='idea',
        ),
    ]
