# Generated by Django 5.0.3 on 2024-04-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_alter_ideaproperty_unique_together_idea_properties_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideaproperty',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='ideaproperty',
            old_name='key',
            new_name='name',
        ),
        migrations.AddField(
            model_name='ideaproperty',
            name='type',
            field=models.CharField(choices=[('integer', 'Integer'), ('text', 'Text')], default='integer', max_length=10),
        ),
        migrations.AlterField(
            model_name='ideaproperty',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
