# Generated by Django 5.0.3 on 2024-04-08 09:00

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_alter_ideaproperty_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='properties',
        ),
        migrations.AddField(
            model_name='idea',
            name='dimensions',
            field=django_jsonform.models.fields.JSONField(blank=True, default=[]),
        ),
        migrations.DeleteModel(
            name='IdeaProperty',
        ),
    ]
