# Generated by Django 5.0.3 on 2024-04-08 09:18

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_remove_idea_properties_idea_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='dimensions',
            field=django_jsonform.models.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='idea',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
